key = "/etc/helium_gateway/key.pem"
listen_addr = "127.0.0.1:1680"
region = "US915"

[log]
method = "stdio"
level = "debug"
timestamp = false

[update]
enabled = true
channel = "release"
interval = 10
platform = "keros"
url = "https://api.github.com/repos/helium/gateway-rs/releases"
